# workflow which will be triggered on a scheduled time basis (UTC)
# Example: Run this workflow every Thursday at 6pm PDT (* 1 * * 4)
# Github action will work on UTC basis, so 6pm PDT in UTC will be 1am and Thursday is every 4th day of the week

#name of workflow
name: Time based workflow

#event which triggers this workflow
on:
    schedule:
        - cron: '30 2 * * *'
    

#list of jobs to run
jobs:
    #Github output
    Testing-time-based:
        #where will this run
        runs-on: ubuntu-latest
        #list of steps to be executed
        steps:
            - name: Hello
              run: echo "Times up"